/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.Enterprise.Enterprise;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.Utils.MyIntegerVerifier;
import Business.Utils.MyPhoneNumberVerifier;
import Business.Utils.MyStringVerifier;
import java.awt.CardLayout;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pamnani
 */
public class EnterDetailsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Patient patient;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form EnterDetailsJPanel
     */
    public EnterDetailsJPanel(JPanel userProcessContainer, UserAccount account, Patient patient, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
        this.enterprise = enterprise;
        this.userAccount = account;
        nameJTxtField.setText(patient.getPersonName());
        MyStringVerifier myStringVerifier= new MyStringVerifier();
//        nameJTxtField.setInputVerifier(myStringVerifier);
        genderJTxtField.setInputVerifier(myStringVerifier);
        addressJTxtField.setInputVerifier(myStringVerifier);
        
        MyPhoneNumberVerifier myPhoneNumberVerifier= new MyPhoneNumberVerifier();
        phoneJTxtField.setInputVerifier(myPhoneNumberVerifier);
        
        MyIntegerVerifier myintegerVerifier= new MyIntegerVerifier();
        ageJTxtField.setInputVerifier(myintegerVerifier);
        if(patient.getAge()!=0)
        {
        populate();
        }
        saveJButton.setEnabled(false);
    }
    
    public void populate()
    {
        
        nameJTxtField.setText(patient.getPersonName());
        ageJTxtField.setText(String.valueOf(patient.getAge()));
        genderJTxtField.setText(patient.getGender());
        addressJTxtField.setText(patient.getPersonAddress());
        phoneJTxtField.setText(String.valueOf(patient.getPhoneNumber()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameJTxtField = new javax.swing.JTextField();
        ageJTxtField = new javax.swing.JTextField();
        genderJTxtField = new javax.swing.JTextField();
        addressJTxtField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        phoneJTxtField = new javax.swing.JTextField();
        editJButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel1.setText("Enter Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/newPatient.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 36, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Details:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setText("Name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, -1, -1));

        jLabel5.setText("Age:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 151, -1, -1));

        jLabel6.setText("Address:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 227, -1, -1));

        jLabel7.setText("Gender:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 189, -1, -1));

        nameJTxtField.setEditable(false);
        add(nameJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 110, 90, -1));

        ageJTxtField.setEnabled(false);
        add(ageJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 148, 90, -1));

        genderJTxtField.setEnabled(false);
        genderJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderJTxtFieldActionPerformed(evt);
            }
        });
        add(genderJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 186, 90, -1));

        addressJTxtField.setEnabled(false);
        addressJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressJTxtFieldActionPerformed(evt);
            }
        });
        add(addressJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 224, 90, -1));

        jLabel8.setText("Phone:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 265, -1, -1));

        phoneJTxtField.setEnabled(false);
        phoneJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneJTxtFieldActionPerformed(evt);
            }
        });
        add(phoneJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 262, 90, -1));

        editJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        editJButton.setText("Edit");
        editJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJButtonActionPerformed(evt);
            }
        });
        add(editJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 321, 72, -1));

        saveJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        saveJButton.setText("Save");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });
        add(saveJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 321, 67, -1));

        backJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 399, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void genderJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderJTxtFieldActionPerformed

    private void addressJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressJTxtFieldActionPerformed

    private void phoneJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneJTxtFieldActionPerformed

    private void editJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJButtonActionPerformed
        // TODO add your handling code here:
        
        ageJTxtField.setEnabled(true);
        genderJTxtField.setEnabled(true);
        addressJTxtField.setEnabled(true);
        phoneJTxtField.setEnabled(true);

        saveJButton.setEnabled(true);
        editJButton.setEnabled(false);
    }//GEN-LAST:event_editJButtonActionPerformed

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:
        if(ageJTxtField.getText().trim().length()==0 || 
                addressJTxtField.getText().length()==0 || genderJTxtField.getText().trim().length()==0 || 
                phoneJTxtField.getText().trim().length() == 0 || ageJTxtField.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Please enter all the values.","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        patient.setAge(Integer.parseInt(ageJTxtField.getText()));
        patient.setGender(genderJTxtField.getText());
        patient.setPersonAddress(addressJTxtField.getText());
        patient.setPhoneNumber(Integer.parseInt(phoneJTxtField.getText()));

        saveJButton.setEnabled(false);
        editJButton.setEnabled(true);
        JOptionPane.showMessageDialog(null, "Patient details updated successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);

        ageJTxtField.setEnabled(false);
        genderJTxtField.setEnabled(false);
        addressJTxtField.setEnabled(false);
        phoneJTxtField.setEnabled(false);

    }//GEN-LAST:event_saveJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressJTxtField;
    private javax.swing.JTextField ageJTxtField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton editJButton;
    private javax.swing.JTextField genderJTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nameJTxtField;
    private javax.swing.JTextField phoneJTxtField;
    private javax.swing.JButton saveJButton;
    // End of variables declaration//GEN-END:variables
}
