/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Patient.Patient;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pamnani
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PatientOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Patient patient;
    private Person person;
    /**
     * Creates new form PatientWorkAreaJPanel
     */
    public PatientWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, PatientOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        
         for(Patient patient:organization.getPatientDirectory().getPatientHistory()) 
          {
            if(patient.getPersonName().equals(userAccount.getPerson().getPersonName()))
              {
              this.patient=patient;
              }
       }
        nameLabel.setText(account.getPerson().getPersonName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        requestJButton = new javax.swing.JButton();
        viewNotificationsJButton = new javax.swing.JButton();
        enterDetailsJButton = new javax.swing.JButton();
        viewRecentReportJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel1.setText("Patient Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        nameLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nameLabel.setText("<<name>>");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 63, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Welcome");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 63, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/patient.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 81, -1, -1));

        requestJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        requestJButton.setText("Request Appointment >>");
        requestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestJButtonActionPerformed(evt);
            }
        });
        add(requestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 173, 197, -1));

        viewNotificationsJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        viewNotificationsJButton.setText("View Notifications >>");
        viewNotificationsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewNotificationsJButtonActionPerformed(evt);
            }
        });
        add(viewNotificationsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 228, 197, -1));

        enterDetailsJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        enterDetailsJButton.setText("Enter / Update Details >>");
        enterDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterDetailsJButtonActionPerformed(evt);
            }
        });
        add(enterDetailsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 117, 197, -1));

        viewRecentReportJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        viewRecentReportJButton.setText("View Most Recent Report >>");
        viewRecentReportJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRecentReportJButtonActionPerformed(evt);
            }
        });
        add(viewRecentReportJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 282, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestJButtonActionPerformed
        // TODO add your handling code here:
         
        if(patient.getHealthStatus().equals("Discharged"))
        {
//            int dialogResult= JOptionPane.showConfirmDialog(this, "Are you Re-addmitted to the Hospital?","Warning", JOptionPane.YES_NO_OPTION);
//            if(dialogResult == JOptionPane.YES_OPTION)
//            {
                JOptionPane.showMessageDialog(this, "You are not an in-patient.You can visit the hospital during visiting hours");
                //patient.setHealthStatus("Admitted");
//            }
//            else
//            {
//                JOptionPane.showMessageDialog(this, "We currently take online appointment for in-patients only.You can visit the hospital during visiting hours");
//            }
        }
        else
        {
        RequestAppointmentJPanel panel = new RequestAppointmentJPanel(userProcessContainer,userAccount,patient, enterprise);
        userProcessContainer.add("RequestAppointment", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_requestJButtonActionPerformed

    private void viewNotificationsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewNotificationsJButtonActionPerformed
        // TODO add your handling code here:
        ViewNotificationsJPanel panel = new ViewNotificationsJPanel(userProcessContainer,userAccount,patient, enterprise);
        userProcessContainer.add("ViewNotifications", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewNotificationsJButtonActionPerformed

    private void enterDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterDetailsJButtonActionPerformed
        // TODO add your handling code here:
        /*int selectedRow= patientJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row from table.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Patient patient=(Patient)patientJTable.getValueAt(selectedRow, 0);
        if(patient.getGender()!=null)
        {
            JOptionPane.showMessageDialog(this, "Patient details have been entered.Click on View Details to edit.", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }*/
        EnterDetailsJPanel panel = new EnterDetailsJPanel(userProcessContainer,userAccount,patient, enterprise);
        userProcessContainer.add("EnterDetails", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_enterDetailsJButtonActionPerformed

    private void viewRecentReportJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRecentReportJButtonActionPerformed
        // TODO add your handling code here:
        if(patient.getDocReport().getDisease() != null)
        {
         ViewRecentReportJPanel panel = new ViewRecentReportJPanel(userProcessContainer,patient, enterprise);
        userProcessContainer.add("ViewRecentReport", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
        }
        else
        {
        JOptionPane.showMessageDialog(this, "No recent report available.", "Information", JOptionPane.INFORMATION_MESSAGE);
        return;  
        }
    }//GEN-LAST:event_viewRecentReportJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterDetailsJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton requestJButton;
    private javax.swing.JButton viewNotificationsJButton;
    private javax.swing.JButton viewRecentReportJButton;
    // End of variables declaration//GEN-END:variables
}
