/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.ReceptionistOrganization;
import Business.Patient.Patient;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import Business.Utils.MyStringVerifier;
import Business.WorkQueue.AppointmentWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pamnani
 */
public class RequestAppointmentJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Patient patient;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form RequestAppointmentJPanel
     */
    public RequestAppointmentJPanel(JPanel userProcessContainer, UserAccount account, Patient patient, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
        this.enterprise = enterprise;
        this.userAccount = account;
        nameLabel.setText(patient.getPersonName());
        MyStringVerifier myStringVerifier= new MyStringVerifier();
        messageJTxtField.setInputVerifier(myStringVerifier);
        requestedTimeJTxtField.setInputVerifier(myStringVerifier);
        populateDoctorComboBox();
    }
    
    public void populateDoctorComboBox()
    {
        doctorJComboBox.removeAllItems();
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) 
        {
            if(org instanceof DoctorOrganization)
            {
                for(Person person:org.getPersonDirectory().getPersonHistory())
                {
                   doctorJComboBox.addItem(person);
                }
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        requestedTimeJTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        messageJTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        requestJButton = new javax.swing.JButton();
        doctorJComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Patient name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel6.setText("Time:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 204, -1, -1));

        nameLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nameLabel.setText("<<name>>");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 70, -1, -1));
        add(requestedTimeJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 201, 180, -1));

        jLabel4.setText("Message :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, -1, -1));

        backJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 331, -1, -1));

        jLabel5.setText("Doctor:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/reqAppointment.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 53, 285, 234));
        add(messageJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 125, 180, -1));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel1.setText("Request Appointment");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        requestJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        requestJButton.setText("Request Appointment");
        requestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestJButtonActionPerformed(evt);
            }
        });
        add(requestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 246, -1, -1));

        doctorJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(doctorJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 163, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void requestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestJButtonActionPerformed
        // TODO add your handling code here:
        String message = messageJTxtField.getText();
        if(messageJTxtField.getText().trim().length()==0 || 
                requestedTimeJTxtField.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Please enter all the values.","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        AppointmentWorkRequest request = new AppointmentWorkRequest();
        String docName = (String)doctorJComboBox.getSelectedItem().toString();
        request.setMessage(message);
        request.setSender(userAccount);
        request.setRequestedTime(requestedTimeJTxtField.getText());
        request.setStatus("Pending");
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(organization instanceof DoctorOrganization)
            {
                for(UserAccount ua :organization.getUserAccountDirectory().getUserAccountList())
                {
                    
                    if(docName.equals(ua.getPerson().getPersonName()))
                    {
                        request.setReceiver(ua);
                    }
                }
            }

        }
        messageJTxtField.setText("");
        requestedTimeJTxtField.setText("");
        JOptionPane.showMessageDialog(this, "Appointment Request Sent to Dr. "+doctorJComboBox.getSelectedItem());
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof ReceptionistOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }

    }//GEN-LAST:event_requestJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox doctorJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField messageJTxtField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton requestJButton;
    private javax.swing.JTextField requestedTimeJTxtField;
    // End of variables declaration//GEN-END:variables
}
