/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PharmacistRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PharmacyOrganization;
import Business.Pharmacy.Drug;
import Business.Pharmacy.DrugCatalog;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Pamnani
 */
public class PharmacistWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private PharmacyOrganization organization;
    
    /**
     * Creates new form PharmacistWorkAreaJPanel
     */
    public PharmacistWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, 
            PharmacyOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        nameLabel.setText(account.getPerson().getPersonName());
       
                //initialize();
    }

//    public void initialize()
//    {
//        DrugCatalog drugCatalog = organization.getDrugCatalog();
//        //Drug d1 = new Drug();
//        drugCatalog.addDrug("Abilify",40);
//        drugCatalog.addDrug("Nexium",61);
//        drugCatalog.addDrug("Humira",61);
//        drugCatalog.addDrug("Crestor",22);
//        drugCatalog.addDrug("Advair",98);
//        drugCatalog.addDrug("Diskus",45);
//        drugCatalog.addDrug("Enbrel",86);
//        drugCatalog.addDrug("Remicade",0);
//        drugCatalog.addDrug("Cymbalta",78);
//        drugCatalog.addDrug("Copaxone",0);
//        drugCatalog.addDrug("Neulasta",72);
//        drugCatalog.addDrug("Lantus",0);
//        drugCatalog.addDrug("Solostar",72);
//        drugCatalog.addDrug("Rituxan",64);
//        drugCatalog.addDrug("Spiriva",31);
//        drugCatalog.addDrug("Handihaler",43);
//        drugCatalog.addDrug("Januvia",40);
//        drugCatalog.addDrug("Atripla",0);
//        drugCatalog.addDrug("Lantus",65);
//        drugCatalog.addDrug("Avastin",35);
//        drugCatalog.addDrug("Lyrica",71);
//        drugCatalog.addDrug("Oxycontin",93);
//        drugCatalog.addDrug("Epogen",0);
//        
//        
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addNewDrugJButton = new javax.swing.JButton();
        viewStoreInvJButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        notificationJButton = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel1.setText("Pharmacist Work Area");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pharmacist.jpg"))); // NOI18N

        addNewDrugJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        addNewDrugJButton.setText("Add  New Drugs >>");
        addNewDrugJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewDrugJButtonActionPerformed(evt);
            }
        });

        viewStoreInvJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        viewStoreInvJButton.setText("View Store Inventory >>");
        viewStoreInvJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStoreInvJButtonActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nameLabel.setText("<<name>>");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Welcome");

        notificationJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        notificationJButton.setText("View Notifications from Doctor >>");
        notificationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(jLabel4)
                                .addGap(10, 10, 10)
                                .addComponent(nameLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(notificationJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(viewStoreInvJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(addNewDrugJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jLabel2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(nameLabel))
                        .addGap(72, 72, 72)
                        .addComponent(addNewDrugJButton)
                        .addGap(28, 28, 28)
                        .addComponent(viewStoreInvJButton)
                        .addGap(33, 33, 33)
                        .addComponent(notificationJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)))
                .addGap(187, 187, 187))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addNewDrugJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewDrugJButtonActionPerformed
        // TODO add your handling code here:
        AddNewDrugsJPanel panel = new AddNewDrugsJPanel(userProcessContainer,userAccount,organization,enterprise);
        userProcessContainer.add("AddNewDrug", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addNewDrugJButtonActionPerformed

    private void viewStoreInvJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStoreInvJButtonActionPerformed
        // TODO add your handling code here:
        ViewDrugsJPanel panel = new ViewDrugsJPanel(userProcessContainer,userAccount,organization,enterprise);
        userProcessContainer.add("ViewDrugs", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewStoreInvJButtonActionPerformed

    private void notificationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationJButtonActionPerformed
        // TODO add your handling code here:
        ViewNotificationsJPanel panel = new ViewNotificationsJPanel(userProcessContainer,userAccount,organization,enterprise);
        userProcessContainer.add("ViewNotifications", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_notificationJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewDrugJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton notificationJButton;
    private javax.swing.JButton viewStoreInvJButton;
    // End of variables declaration//GEN-END:variables
}
