/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NurseRole;

import Business.Enterprise.Enterprise;
import Business.Organization.NurseOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pamnani
 */
public class NurseWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private NurseOrganization nurseOrganization;
    /**
     * Creates new form NurseWorkAreaJPanel
     */
    public NurseWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.nurseOrganization = (NurseOrganization)organization;
        nameLabel.setText(account.getPerson().getPersonName());
        populateTable();
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) patientJTable.getModel();
        model.setRowCount(0);
        
        Organization org = null;
        Object row[] = new Object[2];
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for(Patient patient:organization.getPatientDirectory().getPatientHistory())
                if(patient.getHealthStatus()!= "Discharged")
                {
                 {
                     row[0]=patient;
                     row[1]=patient.getHealthStatus();
                     model.addRow(row);
                 }
                }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientJTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        viewDetailsJButton = new javax.swing.JButton();
        viewVitalSignHistoryJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel1.setText("Nurse Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/nurse.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 69, -1, -1));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 63, -1, -1));

        patientJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        patientJTable.setGridColor(new java.awt.Color(255, 255, 255));
        patientJTable.setOpaque(false);
        patientJTable.setSelectionBackground(new java.awt.Color(51, 255, 204));
        jScrollPane1.setViewportView(patientJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 151, 367, 91));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Patient List:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 111, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Welcome");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 63, -1, -1));

        nameLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nameLabel.setText("<<name>>");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 63, -1, -1));

        viewDetailsJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        viewDetailsJButton.setText("View Details >>");
        viewDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsJButtonActionPerformed(evt);
            }
        });
        add(viewDetailsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 189, -1));

        viewVitalSignHistoryJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        viewVitalSignHistoryJButton.setText("View Vital Sign History >>");
        viewVitalSignHistoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVitalSignHistoryJButtonActionPerformed(evt);
            }
        });
        add(viewVitalSignHistoryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 303, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow= patientJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row from table.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            Patient patient = (Patient)patientJTable.getValueAt(selectedRow, 0);
            if(patient.getGender()!=null)
            {
                ViewDetailsJPanel panel= new ViewDetailsJPanel(userProcessContainer, patient,enterprise.getPatientDirectory(),enterprise);
                userProcessContainer.add("ViewPatientDetails", panel);
                CardLayout layout=(CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                
            }
            else
            {
            JOptionPane.showMessageDialog(this, "Patient details have not been filled.Ensure that the details are filled!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
    }//GEN-LAST:event_viewDetailsJButtonActionPerformed

    private void viewVitalSignHistoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVitalSignHistoryJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow= patientJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row from table.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            Patient patient = (Patient)patientJTable.getValueAt(selectedRow, 0);
            ViewVitalSignHistoryJPanel panel= new ViewVitalSignHistoryJPanel(userProcessContainer, patient,enterprise.getPatientDirectory(),enterprise);
            userProcessContainer.add("ViewPatientDetails", panel);
            CardLayout layout=(CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_viewVitalSignHistoryJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTable patientJTable;
    private javax.swing.JButton viewDetailsJButton;
    private javax.swing.JButton viewVitalSignHistoryJButton;
    // End of variables declaration//GEN-END:variables
}
