/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NurseRole;

import Business.Enterprise.Enterprise;
import Business.Patient.Patient;
import Business.Patient.PatientDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pamnani
 */
public class ViewDetailsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PatientDirectory patientdirectory;
    private Enterprise enterprise;
    private Patient patient;
    /**
     * Creates new form ViewDetailsJPanel
     */
    public ViewDetailsJPanel(JPanel userProcessContainer,Patient patient,
            PatientDirectory patientDirectory,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.patient=patient;
        this.patientdirectory=patientDirectory;
        populate();
    }

    public void populate()
    {
        nameJTxtField.setText(patient.getPersonName());
        ageJTxtField.setText(String.valueOf(patient.getAge()));
        genderJTxtField.setText(patient.getGender());
        addressJTxtField.setText(patient.getPersonAddress());
        phoneTxtField.setText(String.valueOf(patient.getPhoneNumber()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameJTxtField = new javax.swing.JTextField();
        phoneTxtField = new javax.swing.JTextField();
        ageJTxtField = new javax.swing.JTextField();
        genderJTxtField = new javax.swing.JTextField();
        addressJTxtField = new javax.swing.JTextField();
        monitorVitalSignsJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel1.setText("View Patient Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Patient Details :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, -1, -1));

        jLabel4.setText("Name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));

        jLabel5.setText("Age:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 101, -1, -1));

        jLabel6.setText("Address:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 139, -1, -1));

        jLabel7.setText("Gender:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 101, -1, -1));

        jLabel8.setText("Phone Number:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 139, -1, -1));

        nameJTxtField.setEditable(false);
        add(nameJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 98, 90, -1));

        phoneTxtField.setEnabled(false);
        phoneTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTxtFieldActionPerformed(evt);
            }
        });
        add(phoneTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 136, 90, -1));

        ageJTxtField.setEnabled(false);
        add(ageJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 98, 90, -1));

        genderJTxtField.setEnabled(false);
        genderJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderJTxtFieldActionPerformed(evt);
            }
        });
        add(genderJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 98, 90, -1));

        addressJTxtField.setEnabled(false);
        addressJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressJTxtFieldActionPerformed(evt);
            }
        });
        add(addressJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 136, 90, -1));

        monitorVitalSignsJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        monitorVitalSignsJButton.setText("Monitor Vital Signs >>");
        monitorVitalSignsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitorVitalSignsJButtonActionPerformed(evt);
            }
        });
        add(monitorVitalSignsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 199, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/patDetails.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 23, -1, -1));

        backJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 399, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void phoneTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTxtFieldActionPerformed

    private void genderJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderJTxtFieldActionPerformed

    private void addressJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressJTxtFieldActionPerformed

    private void monitorVitalSignsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitorVitalSignsJButtonActionPerformed
        // TODO add your handling code here:
            MonitorVitalSignsJPanel panel= new MonitorVitalSignsJPanel(userProcessContainer, patient,enterprise);
            userProcessContainer.add("MonitorVitalSigns", panel);
            CardLayout layout=(CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_monitorVitalSignsJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressJTxtField;
    private javax.swing.JTextField ageJTxtField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField genderJTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton monitorVitalSignsJButton;
    private javax.swing.JTextField nameJTxtField;
    private javax.swing.JTextField phoneTxtField;
    // End of variables declaration//GEN-END:variables
}
