/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReceptionistRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Organization.ReceptionistOrganization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pamnani
 */
public class CreatePatientJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private ReceptionistOrganization receptionistOrganization;
    private PatientOrganization patientOrganization;
    private Patient patient;
    /**
     * Creates new form CreatePatientJPanel
     */
    public CreatePatientJPanel(JPanel userProcessContainer,Patient patient, Enterprise enterprise, PatientOrganization patientOrganization ) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.patient=patient;
        this.patientOrganization=patientOrganization;
        nameJTxtField.setText(patient.getPersonName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameJTxtField = new javax.swing.JTextField();
        phoneTxtField = new javax.swing.JTextField();
        ageJTxtField = new javax.swing.JTextField();
        genderJTxtField = new javax.swing.JTextField();
        addressJTxtField = new javax.swing.JTextField();
        createJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel1.setText("Create Patient Record");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/newPatient.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 48, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Patient Details");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 70, -1, -1));

        jLabel4.setText("Name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 119, -1, -1));

        jLabel5.setText("Age:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 157, -1, -1));

        jLabel6.setText("Address:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 233, -1, -1));

        jLabel7.setText("Gender:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, -1, -1));

        jLabel8.setText("Phone Number:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 265, -1, -1));

        nameJTxtField.setEditable(false);
        add(nameJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 116, 90, -1));

        phoneTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTxtFieldActionPerformed(evt);
            }
        });
        add(phoneTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 262, 90, -1));
        add(ageJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 154, 90, -1));

        genderJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderJTxtFieldActionPerformed(evt);
            }
        });
        add(genderJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 192, 90, -1));

        addressJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressJTxtFieldActionPerformed(evt);
            }
        });
        add(addressJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 230, 90, -1));

        createJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        createJButton.setText("Create");
        createJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButtonActionPerformed(evt);
            }
        });
        add(createJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 300, -1, -1));

        backJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 381, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void genderJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderJTxtFieldActionPerformed

    private void addressJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressJTxtFieldActionPerformed

    private void phoneTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTxtFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PatientListJPanel panel = (PatientListJPanel) component;
        panel.populatePatientTable();
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void createJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButtonActionPerformed
        // TODO add your handling code here:
        
        Organization org = null;
        for(Organization organization: enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(organization instanceof PatientOrganization)
            {
                org = organization;
                break;
            }
        }
        if(org!=null)
            {
                //for(Patient patient:org.getPatientDirectory().getPatientHistory())
                //{
                //Patient patient= new Patient();
                //org.getPatientDirectory().getPatientHistory().add(patient);
                patient.setPersonName(patient.getPersonName());
                patient.setAge(Integer.parseInt(ageJTxtField.getText()));
                patient.setGender(genderJTxtField.getText());
                patient.setPersonAddress(addressJTxtField.getText());
                patient.setPhoneNumber(Integer.parseInt(phoneTxtField.getText()));
                JOptionPane.showMessageDialog(this, "Patient Details saved!", "Information", JOptionPane.INFORMATION_MESSAGE);
                nameJTxtField.setText("");
                ageJTxtField.setText("");
                genderJTxtField.setText("");
                addressJTxtField.setText("");
                phoneTxtField.setText("");
                //System.out.println(org.getPatientDirectory().getPatientHistory());
               // }
                
            }
    }//GEN-LAST:event_createJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressJTxtField;
    private javax.swing.JTextField ageJTxtField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createJButton;
    private javax.swing.JTextField genderJTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nameJTxtField;
    private javax.swing.JTextField phoneTxtField;
    // End of variables declaration//GEN-END:variables
}
