/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.MayorRole;

import Business.Enterprise.Enterprise;
import Business.Organization.EnvQualityCheckOrganization;
import Business.Organization.MayorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Pamnani
 */
public class MayorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private MayorOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form MayorWorkAreaJPanel
     */
    public MayorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, 
            MayorOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        viewAQHistoryJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel1.setText("Mayor Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/mayor.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 11, -1, -1));

        viewAQHistoryJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        viewAQHistoryJButton.setText("View Air Quality History >>");
        viewAQHistoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAQHistoryJButtonActionPerformed(evt);
            }
        });
        add(viewAQHistoryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 93, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewAQHistoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAQHistoryJButtonActionPerformed
        // TODO add your handling code here:
        
        ViewAQHistoryJPanel panel = new ViewAQHistoryJPanel(userProcessContainer,userAccount,organization,enterprise);
        userProcessContainer.add("ViewAQHistory", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewAQHistoryJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton viewAQHistoryJButton;
    // End of variables declaration//GEN-END:variables
}
