/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AQMonitorsRole;

import Business.Enterprise.Enterprise;
import Business.Organization.EnvQualityCheckOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Pamnani
 */
public class AQMonitorsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EnvQualityCheckOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form AQMonitorsJPanel
     */
    public AQMonitorsJPanel(JPanel userProcessContainer, UserAccount account, EnvQualityCheckOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        currentEnvStats = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel1.setText("Air Quality Monitors");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/AQMonitor.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 34, -1, -1));

        currentEnvStats.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        currentEnvStats.setText("Get Current Environment Statistics >>");
        currentEnvStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentEnvStatsActionPerformed(evt);
            }
        });
        add(currentEnvStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 97, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void currentEnvStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentEnvStatsActionPerformed
        // TODO add your handling code here:
        CurrentEnvStatsJPanel panel = new CurrentEnvStatsJPanel(userProcessContainer,userAccount,organization,enterprise);
        userProcessContainer.add("CurrentEnvStatus", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_currentEnvStatsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton currentEnvStats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
