/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AQMonitorsRole;

import Business.AirQuality.AirQuality;
import Business.Enterprise.Enterprise;
import Business.Organization.EnvQualityCheckOrganization;
import Business.Organization.Organization;
import Business.Organization.ReceptionistOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AQNotifyWorkRequest;
import java.awt.CardLayout;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pamnani
 */
public class CurrentEnvStatsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EnvQualityCheckOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    //private AirQuality airQuality;
    /**
     * Creates new form CurrentEnvStatsJPanel
     */
    public CurrentEnvStatsJPanel(JPanel userProcessContainer,UserAccount userAccount,EnvQualityCheckOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        generate();
        if(statusTxtFiled.getText().equals("Bad Air Quality"))
        {
            reportJButton.setEnabled(true);
        }
    }

    public void generate()
    {
        Random r = new Random();
        int pollutionLevel = r.nextInt(40 - 20)+15;
        int temperature = r.nextInt(68-41)+38;
        int humidity = r.nextInt(80-50)+ 50 ;
        int ventilation = r.nextInt(100-90)+ 90;
        String overallStatus = checkNormal(pollutionLevel, temperature,humidity,ventilation);
        
        pollutionLevelTxtField.setText(String.valueOf(pollutionLevel));
        tempTxtField.setText(String.valueOf(temperature));
        humidityTxtField.setText(String.valueOf(humidity));
        ventilationTxtField.setText(String.valueOf(ventilation));
        statusTxtFiled.setText(overallStatus);
        
 //        AirQuality airQuality = organization.getAirQualityHistory().createAndAddAQ();
        //for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
        organization.getAirQualityHistory().createAndAddAQ(pollutionLevel,temperature,
                humidity,ventilation,overallStatus,new Date());
       
//        airQuality.setPollutionLevel(pollutionLevel);
//        airQuality.setTemperature(temperature);
//        airQuality.setHumidity(humidity);
//        airQuality.setVentilation(ventilation);
//        airQuality.setStatus(overallStatus);
//        airQuality.setMonitoredOn(new Date());
         JOptionPane.showMessageDialog(this, "AirQuality recorded successfully");
         //System.out.println(organization.getAirQualityHistory().getAirQualityHistory().size());
        
        
    }
    
    public String checkNormal(int pollutionLevel,int temperature,int humidity,int ventilation)
    {
        String stat;
        if((pollutionLevel > 20 && pollutionLevel < 40) &&  
                 (temperature > 41 && temperature < 68) && (humidity > 50 && humidity < 80)   
                && (ventilation > 90 && ventilation < 100)    )
        {
            stat ="Good Air Quality";
        }
        else
        {
            stat="Bad Air Quality";
        }
        
        return stat;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        pollutionLevelTxtField = new javax.swing.JTextField();
        tempTxtField = new javax.swing.JTextField();
        humidityTxtField = new javax.swing.JTextField();
        ventilationTxtField = new javax.swing.JTextField();
        statusTxtFiled = new javax.swing.JTextField();
        reportJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel1.setText("Current Environment Statics");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/airpollution.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 70, -1, -1));

        jLabel3.setText("Pollution Level (%)");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 95, 120, -1));

        jLabel4.setText("Temperature (Fahrenheit)");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 133, -1, -1));

        jLabel5.setText("Humidity (%)");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 171, -1, -1));

        jLabel6.setText("Ventilation (%)");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 209, -1, -1));

        jLabel7.setText("Overall Status:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 247, -1, -1));

        backJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 372, -1, -1));

        pollutionLevelTxtField.setEnabled(false);
        add(pollutionLevelTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 92, 112, -1));

        tempTxtField.setEnabled(false);
        add(tempTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 130, 112, -1));

        humidityTxtField.setEnabled(false);
        humidityTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                humidityTxtFieldActionPerformed(evt);
            }
        });
        add(humidityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 168, 112, -1));

        ventilationTxtField.setEnabled(false);
        add(ventilationTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 206, 112, -1));

        statusTxtFiled.setEnabled(false);
        add(statusTxtFiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 244, 112, -1));

        reportJButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        reportJButton.setText("Report >>");
        reportJButton.setEnabled(false);
        reportJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportJButtonActionPerformed(evt);
            }
        });
        add(reportJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 282, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void humidityTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_humidityTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_humidityTxtFieldActionPerformed

    private void reportJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportJButtonActionPerformed
        // TODO add your handling code here:
//        if(statusTxtFiled.getText().equals("Bad Air Quality"))
        
        AQNotifyWorkRequest request = new AQNotifyWorkRequest();
        request.setMessage("The Air Quality around the Hospital is Bad.Please ensure precautions.");
        request.setTrackedOn(new Date());
        JOptionPane.showMessageDialog(this, "Reported to the Organization");
        reportJButton.setEnabled(false);
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof ReceptionistOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        
//        
//        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
//        {
//            
//                String notification = "The Air Quality around the Hospital is Bad.Please ensure precautions.";
//                org.getNotificationList().add(notification);
//                
//        }
//        JOptionPane.showMessageDialog(this, "Reported to the Organization");
//            
    }//GEN-LAST:event_reportJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField humidityTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField pollutionLevelTxtField;
    private javax.swing.JButton reportJButton;
    private javax.swing.JTextField statusTxtFiled;
    private javax.swing.JTextField tempTxtField;
    private javax.swing.JTextField ventilationTxtField;
    // End of variables declaration//GEN-END:variables
}
